version: '3'

services:
  db_postgres:
    image: postgres:10.1
    container_name: jobsity-chat-postgres
    restart: always
    ports:
        - 5432:5432
    volumes:
        - 'postgresql_db:/var/lib/postgresql'
    environment:
        POSTGRES_USER: "root"
        POSTGRES_PASSWORD: "admin"
        POSTGRES_DB: "chat"
volumes:
  postgresql_db:
